-d C:\Users\Nah\Desktop\FPGA\ledblink\impl\gwsynthesis\ledblink.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\Nah\Desktop\FPGA\ledblink\src\counter.cst
-cfg C:\Users\Nah\Desktop\FPGA\ledblink\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
